CREATE TABLE order_table
(
    id              BIGINT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_date    BIGINT             NOT NULL,
    origin          VARCHAR(255),
    destination     VARCHAR(255),
    latitude        DECIMAL,
    longitude       DECIMAL,
    owner_name      varchar(255),
    phone           VARCHAR(64),
    time_of_arrival BIGINT,
    total_sum       DECIMAL
);

INSERT INTO order_table
VALUES (1, 1581162912000, 'origin', 'destination', 0.0, 0.0, 'user_test_name', '+38 096 111 11 11', 1581462912000, 510);

CREATE SEQUENCE hibernate_sequence
INCREMENT 1
START 1;