CREATE TABLE product
(
    id            BIGINT PRIMARY KEY NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    created_date  BIGINT             NOT NULL,
    name          VARCHAR(255),
    cost          DECIMAL,
    weight        DECIMAL,
    time_to_prune BIGINT,
    order_id      BIGINT             NOT NULL
);

ALTER TABLE product
    ADD CONSTRAINT product_order_table_id_fk
        FOREIGN KEY (order_id) REFERENCES order_table (id)
            ON DELETE CASCADE;


INSERT INTO product (id, created_date, name, cost, weight, time_to_prune, order_id)
VALUES (1, 15555555555, 'Milk', 200, 0.5, 155555555567, 1),
       (2, 15555556666, 'Meat', 310, 1, 155555555567, 1);


